services:
  - type: web
    name: test-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
             - key: APP_PASSWORD
               value: cursifyvertex2025
    healthCheckPath: /api/health
    autoDeploy: true
